# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 251563866a9505e3082ac97e13bcba6c5ae77cc6f2328464dc03eacc438786a02d9f4208e0422f96a0fd4b5e3195f7cb573b5e551cdaac0d5aee5e752284854f

test:
  secret_key_base: 88c26f737504f747b105fd49dbad88ee14a25a1871ac26ae04a20e9f930553a436aeb4f215e9cef24787afde0bed992cde298fefe6f0a4b26e5dd84c4e7e8602

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
